name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: notifications
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123455
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -f notification-service/pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/notifications
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: 123455
          SPRING_RABBITMQ_HOST: localhost
          SPRING_DATA_REDIS_HOST: localhost

      - name: Build Docker image
        run: |
          cp notification-service/target/notification-service.jar .
          docker build . -t notification-service:latest